#!/bin/bash
title=am
description="- Installs AM for managing AppImages"
status=off

main() {
    commandFailure="AM dependencies installation has failed." &&
        install curl wget zsync unzip tar

    commandFailure="Download AM installer has failed." &&
        system curl -s https://raw.githubusercontent.com/ivan-hc/AM/refs/heads/main/AM-INSTALLER -o /tmp/AM-INSTALLER

    commandFailure="AM installation has failed." &&
        system chmod a+x /tmp/AM-INSTALLER
        system /tmp/AM-INSTALLER

    return 0
}
